spring:
  jpa:
    show-sql: true
    
  datasource:
    url: jdbc:h2:mem:tiger_card_db
    driverClassName: org.h2.Driver
    username: tiger
    password: tiger
  flyway:
    #user: tiger
    #password: tiger
    baselineOnMigrate: true
    ##schemas: public
    #url: jdbc:h2:mem:tiger_card_db
  h2:
    console:
      enabled: true
  